CREATE TABLE IF NOT EXISTS public.tarefa
(
    codigo bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    usuario bigint,
    CONSTRAINT tarefa_pkey PRIMARY KEY (codigo),
    CONSTRAINT fkjt47q9xtj4n3db2mc8gkee6qr FOREIGN KEY (usuario)
        REFERENCES public.usuario (codigo) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);